namespace DouYonetim.KullanıcıDenetimi
{
    partial class GuncellestirUC
    {
        /// <summary> 
        ///Gerekli tasarımcı değişkeni.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        ///Kullanılan tüm kaynakları temizleyin.
        /// </summary>
        ///<param name="disposing">yönetilen kaynaklar dispose edilmeliyse doğru; aksi halde yanlış.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Bileşen Tasarımcısı üretimi kod

        /// <summary> 
        /// Tasarımcı desteği için gerekli metot - bu metodun 
        ///içeriğini kod düzenleyici ile değiştirmeyin.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GuncellestirUC));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.gncl_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ad_txtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.soyad_txtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.telno_txtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.mailadresi_txtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bolumcombobox = new Bunifu.UI.WinForms.BunifuDropdown();
            this.akademisyencombo = new Bunifu.UI.WinForms.BunifuDropdown();
            this.idtxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.aiguncombobox = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // gncl_btn
            // 
            this.gncl_btn.AllowAnimations = true;
            this.gncl_btn.AllowMouseEffects = true;
            this.gncl_btn.AllowToggling = false;
            this.gncl_btn.AnimationSpeed = 200;
            this.gncl_btn.AutoGenerateColors = false;
            this.gncl_btn.AutoRoundBorders = false;
            this.gncl_btn.AutoSizeLeftIcon = true;
            this.gncl_btn.AutoSizeRightIcon = true;
            this.gncl_btn.BackColor = System.Drawing.Color.Transparent;
            this.gncl_btn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.gncl_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gncl_btn.BackgroundImage")));
            this.gncl_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gncl_btn.ButtonText = "Güncellestir";
            this.gncl_btn.ButtonTextMarginLeft = 0;
            this.gncl_btn.ColorContrastOnClick = 45;
            this.gncl_btn.ColorContrastOnHover = 45;
            this.gncl_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.gncl_btn.CustomizableEdges = borderEdges1;
            this.gncl_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.gncl_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gncl_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gncl_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gncl_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.gncl_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gncl_btn.ForeColor = System.Drawing.Color.White;
            this.gncl_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.gncl_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.gncl_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.gncl_btn.IconMarginLeft = 11;
            this.gncl_btn.IconPadding = 10;
            this.gncl_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.gncl_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.gncl_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.gncl_btn.IconSize = 25;
            this.gncl_btn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.gncl_btn.IdleBorderRadius = 1;
            this.gncl_btn.IdleBorderThickness = 1;
            this.gncl_btn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.gncl_btn.IdleIconLeftImage = null;
            this.gncl_btn.IdleIconRightImage = null;
            this.gncl_btn.IndicateFocus = false;
            this.gncl_btn.Location = new System.Drawing.Point(304, 265);
            this.gncl_btn.Name = "gncl_btn";
            this.gncl_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gncl_btn.OnDisabledState.BorderRadius = 1;
            this.gncl_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gncl_btn.OnDisabledState.BorderThickness = 1;
            this.gncl_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gncl_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gncl_btn.OnDisabledState.IconLeftImage = null;
            this.gncl_btn.OnDisabledState.IconRightImage = null;
            this.gncl_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gncl_btn.onHoverState.BorderRadius = 1;
            this.gncl_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gncl_btn.onHoverState.BorderThickness = 1;
            this.gncl_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gncl_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.gncl_btn.onHoverState.IconLeftImage = null;
            this.gncl_btn.onHoverState.IconRightImage = null;
            this.gncl_btn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.gncl_btn.OnIdleState.BorderRadius = 1;
            this.gncl_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gncl_btn.OnIdleState.BorderThickness = 1;
            this.gncl_btn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.gncl_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.gncl_btn.OnIdleState.IconLeftImage = null;
            this.gncl_btn.OnIdleState.IconRightImage = null;
            this.gncl_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gncl_btn.OnPressedState.BorderRadius = 1;
            this.gncl_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gncl_btn.OnPressedState.BorderThickness = 1;
            this.gncl_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gncl_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.gncl_btn.OnPressedState.IconLeftImage = null;
            this.gncl_btn.OnPressedState.IconRightImage = null;
            this.gncl_btn.Size = new System.Drawing.Size(145, 37);
            this.gncl_btn.TabIndex = 0;
            this.gncl_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gncl_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.gncl_btn.TextMarginLeft = 0;
            this.gncl_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.gncl_btn.UseDefaultRadiusAndThickness = true;
            this.gncl_btn.Click += new System.EventHandler(this.gncl_btn_Click);
            // 
            // ad_txtbox
            // 
            this.ad_txtbox.AcceptsReturn = false;
            this.ad_txtbox.AcceptsTab = false;
            this.ad_txtbox.AnimationSpeed = 200;
            this.ad_txtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ad_txtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ad_txtbox.BackColor = System.Drawing.Color.Transparent;
            this.ad_txtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ad_txtbox.BackgroundImage")));
            this.ad_txtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ad_txtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ad_txtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ad_txtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.ad_txtbox.BorderRadius = 1;
            this.ad_txtbox.BorderThickness = 1;
            this.ad_txtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ad_txtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ad_txtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ad_txtbox.DefaultText = "";
            this.ad_txtbox.FillColor = System.Drawing.Color.White;
            this.ad_txtbox.HideSelection = true;
            this.ad_txtbox.IconLeft = null;
            this.ad_txtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ad_txtbox.IconPadding = 10;
            this.ad_txtbox.IconRight = null;
            this.ad_txtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ad_txtbox.Lines = new string[0];
            this.ad_txtbox.Location = new System.Drawing.Point(68, 120);
            this.ad_txtbox.MaxLength = 32767;
            this.ad_txtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.ad_txtbox.Modified = false;
            this.ad_txtbox.Multiline = false;
            this.ad_txtbox.Name = "ad_txtbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ad_txtbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ad_txtbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ad_txtbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ad_txtbox.OnIdleState = stateProperties4;
            this.ad_txtbox.Padding = new System.Windows.Forms.Padding(3);
            this.ad_txtbox.PasswordChar = '\0';
            this.ad_txtbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ad_txtbox.PlaceholderText = "Ad";
            this.ad_txtbox.ReadOnly = false;
            this.ad_txtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ad_txtbox.SelectedText = "";
            this.ad_txtbox.SelectionLength = 0;
            this.ad_txtbox.SelectionStart = 0;
            this.ad_txtbox.ShortcutsEnabled = true;
            this.ad_txtbox.Size = new System.Drawing.Size(164, 37);
            this.ad_txtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ad_txtbox.TabIndex = 1;
            this.ad_txtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ad_txtbox.TextMarginBottom = 0;
            this.ad_txtbox.TextMarginLeft = 3;
            this.ad_txtbox.TextMarginTop = 0;
            this.ad_txtbox.TextPlaceholder = "Ad";
            this.ad_txtbox.UseSystemPasswordChar = false;
            this.ad_txtbox.WordWrap = true;
            // 
            // soyad_txtbox
            // 
            this.soyad_txtbox.AcceptsReturn = false;
            this.soyad_txtbox.AcceptsTab = false;
            this.soyad_txtbox.AnimationSpeed = 200;
            this.soyad_txtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.soyad_txtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.soyad_txtbox.BackColor = System.Drawing.Color.Transparent;
            this.soyad_txtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("soyad_txtbox.BackgroundImage")));
            this.soyad_txtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.soyad_txtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.soyad_txtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.soyad_txtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.soyad_txtbox.BorderRadius = 1;
            this.soyad_txtbox.BorderThickness = 1;
            this.soyad_txtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.soyad_txtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.soyad_txtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.soyad_txtbox.DefaultText = "";
            this.soyad_txtbox.FillColor = System.Drawing.Color.White;
            this.soyad_txtbox.HideSelection = true;
            this.soyad_txtbox.IconLeft = null;
            this.soyad_txtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.soyad_txtbox.IconPadding = 10;
            this.soyad_txtbox.IconRight = null;
            this.soyad_txtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.soyad_txtbox.Lines = new string[0];
            this.soyad_txtbox.Location = new System.Drawing.Point(68, 177);
            this.soyad_txtbox.MaxLength = 32767;
            this.soyad_txtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.soyad_txtbox.Modified = false;
            this.soyad_txtbox.Multiline = false;
            this.soyad_txtbox.Name = "soyad_txtbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.soyad_txtbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.soyad_txtbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.soyad_txtbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.soyad_txtbox.OnIdleState = stateProperties8;
            this.soyad_txtbox.Padding = new System.Windows.Forms.Padding(3);
            this.soyad_txtbox.PasswordChar = '\0';
            this.soyad_txtbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.soyad_txtbox.PlaceholderText = "Soyad";
            this.soyad_txtbox.ReadOnly = false;
            this.soyad_txtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.soyad_txtbox.SelectedText = "";
            this.soyad_txtbox.SelectionLength = 0;
            this.soyad_txtbox.SelectionStart = 0;
            this.soyad_txtbox.ShortcutsEnabled = true;
            this.soyad_txtbox.Size = new System.Drawing.Size(164, 37);
            this.soyad_txtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.soyad_txtbox.TabIndex = 2;
            this.soyad_txtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.soyad_txtbox.TextMarginBottom = 0;
            this.soyad_txtbox.TextMarginLeft = 3;
            this.soyad_txtbox.TextMarginTop = 0;
            this.soyad_txtbox.TextPlaceholder = "Soyad";
            this.soyad_txtbox.UseSystemPasswordChar = false;
            this.soyad_txtbox.WordWrap = true;
            // 
            // telno_txtbox
            // 
            this.telno_txtbox.AcceptsReturn = false;
            this.telno_txtbox.AcceptsTab = false;
            this.telno_txtbox.AnimationSpeed = 200;
            this.telno_txtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.telno_txtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.telno_txtbox.BackColor = System.Drawing.Color.Transparent;
            this.telno_txtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("telno_txtbox.BackgroundImage")));
            this.telno_txtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.telno_txtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.telno_txtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.telno_txtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.telno_txtbox.BorderRadius = 1;
            this.telno_txtbox.BorderThickness = 1;
            this.telno_txtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.telno_txtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.telno_txtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.telno_txtbox.DefaultText = "";
            this.telno_txtbox.FillColor = System.Drawing.Color.White;
            this.telno_txtbox.HideSelection = true;
            this.telno_txtbox.IconLeft = null;
            this.telno_txtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.telno_txtbox.IconPadding = 10;
            this.telno_txtbox.IconRight = null;
            this.telno_txtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.telno_txtbox.Lines = new string[0];
            this.telno_txtbox.Location = new System.Drawing.Point(68, 237);
            this.telno_txtbox.MaxLength = 32767;
            this.telno_txtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.telno_txtbox.Modified = false;
            this.telno_txtbox.Multiline = false;
            this.telno_txtbox.Name = "telno_txtbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telno_txtbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.telno_txtbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telno_txtbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telno_txtbox.OnIdleState = stateProperties12;
            this.telno_txtbox.Padding = new System.Windows.Forms.Padding(3);
            this.telno_txtbox.PasswordChar = '\0';
            this.telno_txtbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.telno_txtbox.PlaceholderText = "Telefon Numarası";
            this.telno_txtbox.ReadOnly = false;
            this.telno_txtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.telno_txtbox.SelectedText = "";
            this.telno_txtbox.SelectionLength = 0;
            this.telno_txtbox.SelectionStart = 0;
            this.telno_txtbox.ShortcutsEnabled = true;
            this.telno_txtbox.Size = new System.Drawing.Size(164, 37);
            this.telno_txtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.telno_txtbox.TabIndex = 3;
            this.telno_txtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.telno_txtbox.TextMarginBottom = 0;
            this.telno_txtbox.TextMarginLeft = 3;
            this.telno_txtbox.TextMarginTop = 0;
            this.telno_txtbox.TextPlaceholder = "Telefon Numarası";
            this.telno_txtbox.UseSystemPasswordChar = false;
            this.telno_txtbox.WordWrap = true;
            // 
            // mailadresi_txtbox
            // 
            this.mailadresi_txtbox.AcceptsReturn = false;
            this.mailadresi_txtbox.AcceptsTab = false;
            this.mailadresi_txtbox.AnimationSpeed = 200;
            this.mailadresi_txtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.mailadresi_txtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.mailadresi_txtbox.BackColor = System.Drawing.Color.White;
            this.mailadresi_txtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mailadresi_txtbox.BackgroundImage")));
            this.mailadresi_txtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.mailadresi_txtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mailadresi_txtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.mailadresi_txtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.mailadresi_txtbox.BorderRadius = 1;
            this.mailadresi_txtbox.BorderThickness = 1;
            this.mailadresi_txtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.mailadresi_txtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.mailadresi_txtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.mailadresi_txtbox.DefaultText = "";
            this.mailadresi_txtbox.FillColor = System.Drawing.Color.White;
            this.mailadresi_txtbox.HideSelection = true;
            this.mailadresi_txtbox.IconLeft = null;
            this.mailadresi_txtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.mailadresi_txtbox.IconPadding = 10;
            this.mailadresi_txtbox.IconRight = null;
            this.mailadresi_txtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.mailadresi_txtbox.Lines = new string[0];
            this.mailadresi_txtbox.Location = new System.Drawing.Point(70, 292);
            this.mailadresi_txtbox.MaxLength = 32767;
            this.mailadresi_txtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.mailadresi_txtbox.Modified = false;
            this.mailadresi_txtbox.Multiline = false;
            this.mailadresi_txtbox.Name = "mailadresi_txtbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mailadresi_txtbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.mailadresi_txtbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mailadresi_txtbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mailadresi_txtbox.OnIdleState = stateProperties16;
            this.mailadresi_txtbox.Padding = new System.Windows.Forms.Padding(3);
            this.mailadresi_txtbox.PasswordChar = '\0';
            this.mailadresi_txtbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.mailadresi_txtbox.PlaceholderText = "Mail Adresi";
            this.mailadresi_txtbox.ReadOnly = false;
            this.mailadresi_txtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.mailadresi_txtbox.SelectedText = "";
            this.mailadresi_txtbox.SelectionLength = 0;
            this.mailadresi_txtbox.SelectionStart = 0;
            this.mailadresi_txtbox.ShortcutsEnabled = true;
            this.mailadresi_txtbox.Size = new System.Drawing.Size(164, 37);
            this.mailadresi_txtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.mailadresi_txtbox.TabIndex = 4;
            this.mailadresi_txtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.mailadresi_txtbox.TextMarginBottom = 0;
            this.mailadresi_txtbox.TextMarginLeft = 3;
            this.mailadresi_txtbox.TextMarginTop = 0;
            this.mailadresi_txtbox.TextPlaceholder = "Mail Adresi";
            this.mailadresi_txtbox.UseSystemPasswordChar = false;
            this.mailadresi_txtbox.WordWrap = true;
            // 
            // bolumcombobox
            // 
            this.bolumcombobox.BackColor = System.Drawing.Color.Transparent;
            this.bolumcombobox.BackgroundColor = System.Drawing.Color.White;
            this.bolumcombobox.BorderColor = System.Drawing.Color.Silver;
            this.bolumcombobox.BorderRadius = 1;
            this.bolumcombobox.Color = System.Drawing.Color.Silver;
            this.bolumcombobox.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bolumcombobox.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bolumcombobox.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bolumcombobox.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bolumcombobox.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bolumcombobox.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bolumcombobox.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bolumcombobox.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bolumcombobox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bolumcombobox.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bolumcombobox.FillDropDown = true;
            this.bolumcombobox.FillIndicator = false;
            this.bolumcombobox.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bolumcombobox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bolumcombobox.ForeColor = System.Drawing.Color.Black;
            this.bolumcombobox.FormattingEnabled = true;
            this.bolumcombobox.Icon = null;
            this.bolumcombobox.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bolumcombobox.IndicatorColor = System.Drawing.Color.Gray;
            this.bolumcombobox.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bolumcombobox.ItemBackColor = System.Drawing.Color.White;
            this.bolumcombobox.ItemBorderColor = System.Drawing.Color.White;
            this.bolumcombobox.ItemForeColor = System.Drawing.Color.Black;
            this.bolumcombobox.ItemHeight = 26;
            this.bolumcombobox.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.bolumcombobox.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bolumcombobox.ItemTopMargin = 3;
            this.bolumcombobox.Location = new System.Drawing.Point(70, 18);
            this.bolumcombobox.Name = "bolumcombobox";
            this.bolumcombobox.Size = new System.Drawing.Size(162, 32);
            this.bolumcombobox.TabIndex = 5;
            this.bolumcombobox.Text = "Bölüm Seçiniz";
            this.bolumcombobox.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bolumcombobox.TextLeftMargin = 5;
            this.bolumcombobox.SelectedIndexChanged += new System.EventHandler(this.bolumcombobox_SelectedIndexChanged);
            // 
            // akademisyencombo
            // 
            this.akademisyencombo.BackColor = System.Drawing.Color.Transparent;
            this.akademisyencombo.BackgroundColor = System.Drawing.Color.White;
            this.akademisyencombo.BorderColor = System.Drawing.Color.Silver;
            this.akademisyencombo.BorderRadius = 1;
            this.akademisyencombo.Color = System.Drawing.Color.Silver;
            this.akademisyencombo.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.akademisyencombo.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.akademisyencombo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.akademisyencombo.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.akademisyencombo.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.akademisyencombo.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.akademisyencombo.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.akademisyencombo.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.akademisyencombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.akademisyencombo.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.akademisyencombo.FillDropDown = true;
            this.akademisyencombo.FillIndicator = false;
            this.akademisyencombo.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.akademisyencombo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.akademisyencombo.ForeColor = System.Drawing.Color.Black;
            this.akademisyencombo.FormattingEnabled = true;
            this.akademisyencombo.Icon = null;
            this.akademisyencombo.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.akademisyencombo.IndicatorColor = System.Drawing.Color.Gray;
            this.akademisyencombo.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.akademisyencombo.ItemBackColor = System.Drawing.Color.White;
            this.akademisyencombo.ItemBorderColor = System.Drawing.Color.White;
            this.akademisyencombo.ItemForeColor = System.Drawing.Color.Black;
            this.akademisyencombo.ItemHeight = 26;
            this.akademisyencombo.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.akademisyencombo.ItemHighLightForeColor = System.Drawing.Color.White;
            this.akademisyencombo.ItemTopMargin = 3;
            this.akademisyencombo.Location = new System.Drawing.Point(70, 72);
            this.akademisyencombo.Name = "akademisyencombo";
            this.akademisyencombo.Size = new System.Drawing.Size(162, 32);
            this.akademisyencombo.TabIndex = 9;
            this.akademisyencombo.Text = "Akademisyen Seçiniz";
            this.akademisyencombo.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.akademisyencombo.TextLeftMargin = 5;
            this.akademisyencombo.SelectedIndexChanged += new System.EventHandler(this.akademisyencombo_SelectedIndexChanged);
            // 
            // idtxtbox
            // 
            this.idtxtbox.AcceptsReturn = false;
            this.idtxtbox.AcceptsTab = false;
            this.idtxtbox.AnimationSpeed = 200;
            this.idtxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idtxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idtxtbox.BackColor = System.Drawing.Color.Transparent;
            this.idtxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idtxtbox.BackgroundImage")));
            this.idtxtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idtxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idtxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idtxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.idtxtbox.BorderRadius = 1;
            this.idtxtbox.BorderThickness = 1;
            this.idtxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idtxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idtxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.idtxtbox.DefaultText = "";
            this.idtxtbox.FillColor = System.Drawing.Color.White;
            this.idtxtbox.HideSelection = true;
            this.idtxtbox.IconLeft = null;
            this.idtxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idtxtbox.IconPadding = 10;
            this.idtxtbox.IconRight = null;
            this.idtxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idtxtbox.Lines = new string[0];
            this.idtxtbox.Location = new System.Drawing.Point(20, 120);
            this.idtxtbox.MaxLength = 32767;
            this.idtxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.idtxtbox.Modified = false;
            this.idtxtbox.Multiline = false;
            this.idtxtbox.Name = "idtxtbox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idtxtbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idtxtbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idtxtbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idtxtbox.OnIdleState = stateProperties20;
            this.idtxtbox.Padding = new System.Windows.Forms.Padding(3);
            this.idtxtbox.PasswordChar = '\0';
            this.idtxtbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idtxtbox.PlaceholderText = "Id";
            this.idtxtbox.ReadOnly = false;
            this.idtxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idtxtbox.SelectedText = "";
            this.idtxtbox.SelectionLength = 0;
            this.idtxtbox.SelectionStart = 0;
            this.idtxtbox.ShortcutsEnabled = true;
            this.idtxtbox.Size = new System.Drawing.Size(42, 37);
            this.idtxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idtxtbox.TabIndex = 23;
            this.idtxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idtxtbox.TextMarginBottom = 0;
            this.idtxtbox.TextMarginLeft = 3;
            this.idtxtbox.TextMarginTop = 0;
            this.idtxtbox.TextPlaceholder = "Id";
            this.idtxtbox.UseSystemPasswordChar = false;
            this.idtxtbox.WordWrap = true;
            // 
            // aiguncombobox
            // 
            this.aiguncombobox.BackColor = System.Drawing.Color.Transparent;
            this.aiguncombobox.BackgroundColor = System.Drawing.Color.White;
            this.aiguncombobox.BorderColor = System.Drawing.Color.Silver;
            this.aiguncombobox.BorderRadius = 1;
            this.aiguncombobox.Color = System.Drawing.Color.Silver;
            this.aiguncombobox.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.aiguncombobox.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.aiguncombobox.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.aiguncombobox.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.aiguncombobox.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.aiguncombobox.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.aiguncombobox.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.aiguncombobox.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.aiguncombobox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.aiguncombobox.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.aiguncombobox.FillDropDown = true;
            this.aiguncombobox.FillIndicator = false;
            this.aiguncombobox.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.aiguncombobox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.aiguncombobox.ForeColor = System.Drawing.Color.Black;
            this.aiguncombobox.FormattingEnabled = true;
            this.aiguncombobox.Icon = null;
            this.aiguncombobox.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.aiguncombobox.IndicatorColor = System.Drawing.Color.Gray;
            this.aiguncombobox.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.aiguncombobox.ItemBackColor = System.Drawing.Color.White;
            this.aiguncombobox.ItemBorderColor = System.Drawing.Color.White;
            this.aiguncombobox.ItemForeColor = System.Drawing.Color.Black;
            this.aiguncombobox.ItemHeight = 26;
            this.aiguncombobox.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.aiguncombobox.ItemHighLightForeColor = System.Drawing.Color.White;
            this.aiguncombobox.ItemTopMargin = 3;
            this.aiguncombobox.Location = new System.Drawing.Point(304, 177);
            this.aiguncombobox.Name = "aiguncombobox";
            this.aiguncombobox.Size = new System.Drawing.Size(145, 32);
            this.aiguncombobox.TabIndex = 22;
            this.aiguncombobox.Text = "Akademik İzin Günü";
            this.aiguncombobox.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.aiguncombobox.TextLeftMargin = 5;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 62;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(317, 16);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(125, 125);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 24;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // GuncellestirUC
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.idtxtbox);
            this.Controls.Add(this.aiguncombobox);
            this.Controls.Add(this.akademisyencombo);
            this.Controls.Add(this.bolumcombobox);
            this.Controls.Add(this.mailadresi_txtbox);
            this.Controls.Add(this.telno_txtbox);
            this.Controls.Add(this.soyad_txtbox);
            this.Controls.Add(this.ad_txtbox);
            this.Controls.Add(this.gncl_btn);
            this.Name = "GuncellestirUC";
            this.Size = new System.Drawing.Size(497, 351);
            this.Load += new System.EventHandler(this.GuncellestirUC_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton gncl_btn;
        private Bunifu.UI.WinForms.BunifuTextBox ad_txtbox;
        private Bunifu.UI.WinForms.BunifuTextBox soyad_txtbox;
        private Bunifu.UI.WinForms.BunifuTextBox telno_txtbox;
        private Bunifu.UI.WinForms.BunifuTextBox mailadresi_txtbox;
        private Bunifu.UI.WinForms.BunifuDropdown bolumcombobox;
        private Bunifu.UI.WinForms.BunifuDropdown akademisyencombo;
        private Bunifu.UI.WinForms.BunifuTextBox idtxtbox;
        private Bunifu.UI.WinForms.BunifuDropdown aiguncombobox;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}
