namespace DouYonetim
{
    partial class AnaSayfa
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AnaSayfa));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.usercontrl = new System.Windows.Forms.Panel();
            this.gnbzli_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.prgrmbaz_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.isrtbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.adara_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tariharamabtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cksbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.backbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // usercontrl
            // 
            this.usercontrl.Location = new System.Drawing.Point(115, 87);
            this.usercontrl.Name = "usercontrl";
            this.usercontrl.Size = new System.Drawing.Size(614, 401);
            this.usercontrl.TabIndex = 8;
            // 
            // gnbzli_btn
            // 
            this.gnbzli_btn.AllowAnimations = true;
            this.gnbzli_btn.AllowMouseEffects = true;
            this.gnbzli_btn.AllowToggling = false;
            this.gnbzli_btn.AnimationSpeed = 200;
            this.gnbzli_btn.AutoGenerateColors = false;
            this.gnbzli_btn.AutoRoundBorders = false;
            this.gnbzli_btn.AutoSizeLeftIcon = true;
            this.gnbzli_btn.AutoSizeRightIcon = true;
            this.gnbzli_btn.BackColor = System.Drawing.Color.Transparent;
            this.gnbzli_btn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.gnbzli_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gnbzli_btn.BackgroundImage")));
            this.gnbzli_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnbzli_btn.ButtonText = "Gün Bazlı Arama";
            this.gnbzli_btn.ButtonTextMarginLeft = 0;
            this.gnbzli_btn.ColorContrastOnClick = 45;
            this.gnbzli_btn.ColorContrastOnHover = 45;
            this.gnbzli_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.gnbzli_btn.CustomizableEdges = borderEdges1;
            this.gnbzli_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.gnbzli_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gnbzli_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gnbzli_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gnbzli_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.gnbzli_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gnbzli_btn.ForeColor = System.Drawing.Color.White;
            this.gnbzli_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.gnbzli_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.gnbzli_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.gnbzli_btn.IconMarginLeft = 11;
            this.gnbzli_btn.IconPadding = 10;
            this.gnbzli_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.gnbzli_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.gnbzli_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.gnbzli_btn.IconSize = 25;
            this.gnbzli_btn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.gnbzli_btn.IdleBorderRadius = 1;
            this.gnbzli_btn.IdleBorderThickness = 1;
            this.gnbzli_btn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.gnbzli_btn.IdleIconLeftImage = null;
            this.gnbzli_btn.IdleIconRightImage = null;
            this.gnbzli_btn.IndicateFocus = false;
            this.gnbzli_btn.Location = new System.Drawing.Point(24, 49);
            this.gnbzli_btn.Name = "gnbzli_btn";
            this.gnbzli_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gnbzli_btn.OnDisabledState.BorderRadius = 1;
            this.gnbzli_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnbzli_btn.OnDisabledState.BorderThickness = 1;
            this.gnbzli_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gnbzli_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gnbzli_btn.OnDisabledState.IconLeftImage = null;
            this.gnbzli_btn.OnDisabledState.IconRightImage = null;
            this.gnbzli_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gnbzli_btn.onHoverState.BorderRadius = 1;
            this.gnbzli_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnbzli_btn.onHoverState.BorderThickness = 1;
            this.gnbzli_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gnbzli_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.gnbzli_btn.onHoverState.IconLeftImage = null;
            this.gnbzli_btn.onHoverState.IconRightImage = null;
            this.gnbzli_btn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.gnbzli_btn.OnIdleState.BorderRadius = 1;
            this.gnbzli_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnbzli_btn.OnIdleState.BorderThickness = 1;
            this.gnbzli_btn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.gnbzli_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.gnbzli_btn.OnIdleState.IconLeftImage = null;
            this.gnbzli_btn.OnIdleState.IconRightImage = null;
            this.gnbzli_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gnbzli_btn.OnPressedState.BorderRadius = 1;
            this.gnbzli_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnbzli_btn.OnPressedState.BorderThickness = 1;
            this.gnbzli_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gnbzli_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.gnbzli_btn.OnPressedState.IconLeftImage = null;
            this.gnbzli_btn.OnPressedState.IconRightImage = null;
            this.gnbzli_btn.Size = new System.Drawing.Size(145, 27);
            this.gnbzli_btn.TabIndex = 17;
            this.gnbzli_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gnbzli_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.gnbzli_btn.TextMarginLeft = 0;
            this.gnbzli_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.gnbzli_btn.UseDefaultRadiusAndThickness = true;
            this.gnbzli_btn.Click += new System.EventHandler(this.gnbzli_btn_Click);
            // 
            // prgrmbaz_btn
            // 
            this.prgrmbaz_btn.AllowAnimations = true;
            this.prgrmbaz_btn.AllowMouseEffects = true;
            this.prgrmbaz_btn.AllowToggling = false;
            this.prgrmbaz_btn.AnimationSpeed = 200;
            this.prgrmbaz_btn.AutoGenerateColors = false;
            this.prgrmbaz_btn.AutoRoundBorders = false;
            this.prgrmbaz_btn.AutoSizeLeftIcon = true;
            this.prgrmbaz_btn.AutoSizeRightIcon = true;
            this.prgrmbaz_btn.BackColor = System.Drawing.Color.Transparent;
            this.prgrmbaz_btn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.prgrmbaz_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prgrmbaz_btn.BackgroundImage")));
            this.prgrmbaz_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.prgrmbaz_btn.ButtonText = "Program Bazlı Arama";
            this.prgrmbaz_btn.ButtonTextMarginLeft = 0;
            this.prgrmbaz_btn.ColorContrastOnClick = 45;
            this.prgrmbaz_btn.ColorContrastOnHover = 45;
            this.prgrmbaz_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.prgrmbaz_btn.CustomizableEdges = borderEdges2;
            this.prgrmbaz_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.prgrmbaz_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.prgrmbaz_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prgrmbaz_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.prgrmbaz_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.prgrmbaz_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.prgrmbaz_btn.ForeColor = System.Drawing.Color.White;
            this.prgrmbaz_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.prgrmbaz_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.prgrmbaz_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.prgrmbaz_btn.IconMarginLeft = 11;
            this.prgrmbaz_btn.IconPadding = 10;
            this.prgrmbaz_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.prgrmbaz_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.prgrmbaz_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.prgrmbaz_btn.IconSize = 25;
            this.prgrmbaz_btn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.prgrmbaz_btn.IdleBorderRadius = 1;
            this.prgrmbaz_btn.IdleBorderThickness = 1;
            this.prgrmbaz_btn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.prgrmbaz_btn.IdleIconLeftImage = null;
            this.prgrmbaz_btn.IdleIconRightImage = null;
            this.prgrmbaz_btn.IndicateFocus = false;
            this.prgrmbaz_btn.Location = new System.Drawing.Point(225, 49);
            this.prgrmbaz_btn.Name = "prgrmbaz_btn";
            this.prgrmbaz_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.prgrmbaz_btn.OnDisabledState.BorderRadius = 1;
            this.prgrmbaz_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.prgrmbaz_btn.OnDisabledState.BorderThickness = 1;
            this.prgrmbaz_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prgrmbaz_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.prgrmbaz_btn.OnDisabledState.IconLeftImage = null;
            this.prgrmbaz_btn.OnDisabledState.IconRightImage = null;
            this.prgrmbaz_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.prgrmbaz_btn.onHoverState.BorderRadius = 1;
            this.prgrmbaz_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.prgrmbaz_btn.onHoverState.BorderThickness = 1;
            this.prgrmbaz_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.prgrmbaz_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.prgrmbaz_btn.onHoverState.IconLeftImage = null;
            this.prgrmbaz_btn.onHoverState.IconRightImage = null;
            this.prgrmbaz_btn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.prgrmbaz_btn.OnIdleState.BorderRadius = 1;
            this.prgrmbaz_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.prgrmbaz_btn.OnIdleState.BorderThickness = 1;
            this.prgrmbaz_btn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.prgrmbaz_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.prgrmbaz_btn.OnIdleState.IconLeftImage = null;
            this.prgrmbaz_btn.OnIdleState.IconRightImage = null;
            this.prgrmbaz_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.prgrmbaz_btn.OnPressedState.BorderRadius = 1;
            this.prgrmbaz_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.prgrmbaz_btn.OnPressedState.BorderThickness = 1;
            this.prgrmbaz_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.prgrmbaz_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.prgrmbaz_btn.OnPressedState.IconLeftImage = null;
            this.prgrmbaz_btn.OnPressedState.IconRightImage = null;
            this.prgrmbaz_btn.Size = new System.Drawing.Size(145, 27);
            this.prgrmbaz_btn.TabIndex = 18;
            this.prgrmbaz_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.prgrmbaz_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.prgrmbaz_btn.TextMarginLeft = 0;
            this.prgrmbaz_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.prgrmbaz_btn.UseDefaultRadiusAndThickness = true;
            this.prgrmbaz_btn.Click += new System.EventHandler(this.prgrmbaz_btn_Click);
            // 
            // isrtbtn
            // 
            this.isrtbtn.AllowAnimations = true;
            this.isrtbtn.AllowMouseEffects = true;
            this.isrtbtn.AllowToggling = false;
            this.isrtbtn.AnimationSpeed = 200;
            this.isrtbtn.AutoGenerateColors = false;
            this.isrtbtn.AutoRoundBorders = false;
            this.isrtbtn.AutoSizeLeftIcon = true;
            this.isrtbtn.AutoSizeRightIcon = true;
            this.isrtbtn.BackColor = System.Drawing.Color.Transparent;
            this.isrtbtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("isrtbtn.BackgroundImage")));
            this.isrtbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.ButtonText = "";
            this.isrtbtn.ButtonTextMarginLeft = 0;
            this.isrtbtn.ColorContrastOnClick = 45;
            this.isrtbtn.ColorContrastOnHover = 45;
            this.isrtbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.isrtbtn.CustomizableEdges = borderEdges3;
            this.isrtbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.isrtbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.isrtbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isrtbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.isrtbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.isrtbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.isrtbtn.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.isrtbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.isrtbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.isrtbtn.IconMarginLeft = 11;
            this.isrtbtn.IconPadding = 10;
            this.isrtbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.isrtbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.isrtbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.isrtbtn.IconSize = 25;
            this.isrtbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.isrtbtn.IdleBorderRadius = 1;
            this.isrtbtn.IdleBorderThickness = 1;
            this.isrtbtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.IdleIconLeftImage = null;
            this.isrtbtn.IdleIconRightImage = null;
            this.isrtbtn.IndicateFocus = false;
            this.isrtbtn.Location = new System.Drawing.Point(221, 45);
            this.isrtbtn.Name = "isrtbtn";
            this.isrtbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.isrtbtn.OnDisabledState.BorderRadius = 1;
            this.isrtbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnDisabledState.BorderThickness = 1;
            this.isrtbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isrtbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.isrtbtn.OnDisabledState.IconLeftImage = null;
            this.isrtbtn.OnDisabledState.IconRightImage = null;
            this.isrtbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isrtbtn.onHoverState.BorderRadius = 1;
            this.isrtbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.onHoverState.BorderThickness = 1;
            this.isrtbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isrtbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.onHoverState.IconLeftImage = null;
            this.isrtbtn.onHoverState.IconRightImage = null;
            this.isrtbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.isrtbtn.OnIdleState.BorderRadius = 1;
            this.isrtbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnIdleState.BorderThickness = 1;
            this.isrtbtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.OnIdleState.IconLeftImage = null;
            this.isrtbtn.OnIdleState.IconRightImage = null;
            this.isrtbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.isrtbtn.OnPressedState.BorderRadius = 1;
            this.isrtbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnPressedState.BorderThickness = 1;
            this.isrtbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.isrtbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.OnPressedState.IconLeftImage = null;
            this.isrtbtn.OnPressedState.IconRightImage = null;
            this.isrtbtn.Size = new System.Drawing.Size(153, 36);
            this.isrtbtn.TabIndex = 21;
            this.isrtbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.isrtbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.isrtbtn.TextMarginLeft = 0;
            this.isrtbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.isrtbtn.UseDefaultRadiusAndThickness = true;
            // 
            // adara_btn
            // 
            this.adara_btn.AllowAnimations = true;
            this.adara_btn.AllowMouseEffects = true;
            this.adara_btn.AllowToggling = false;
            this.adara_btn.AnimationSpeed = 200;
            this.adara_btn.AutoGenerateColors = false;
            this.adara_btn.AutoRoundBorders = false;
            this.adara_btn.AutoSizeLeftIcon = true;
            this.adara_btn.AutoSizeRightIcon = true;
            this.adara_btn.BackColor = System.Drawing.Color.Transparent;
            this.adara_btn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.adara_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adara_btn.BackgroundImage")));
            this.adara_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.adara_btn.ButtonText = "İsim\'e Göre Arama";
            this.adara_btn.ButtonTextMarginLeft = 0;
            this.adara_btn.ColorContrastOnClick = 45;
            this.adara_btn.ColorContrastOnHover = 45;
            this.adara_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.adara_btn.CustomizableEdges = borderEdges4;
            this.adara_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.adara_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.adara_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adara_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.adara_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.adara_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.adara_btn.ForeColor = System.Drawing.Color.White;
            this.adara_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.adara_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.adara_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.adara_btn.IconMarginLeft = 11;
            this.adara_btn.IconPadding = 10;
            this.adara_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.adara_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.adara_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.adara_btn.IconSize = 25;
            this.adara_btn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.adara_btn.IdleBorderRadius = 1;
            this.adara_btn.IdleBorderThickness = 1;
            this.adara_btn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.adara_btn.IdleIconLeftImage = null;
            this.adara_btn.IdleIconRightImage = null;
            this.adara_btn.IndicateFocus = false;
            this.adara_btn.Location = new System.Drawing.Point(426, 49);
            this.adara_btn.Name = "adara_btn";
            this.adara_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.adara_btn.OnDisabledState.BorderRadius = 1;
            this.adara_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.adara_btn.OnDisabledState.BorderThickness = 1;
            this.adara_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adara_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.adara_btn.OnDisabledState.IconLeftImage = null;
            this.adara_btn.OnDisabledState.IconRightImage = null;
            this.adara_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.adara_btn.onHoverState.BorderRadius = 1;
            this.adara_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.adara_btn.onHoverState.BorderThickness = 1;
            this.adara_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.adara_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.adara_btn.onHoverState.IconLeftImage = null;
            this.adara_btn.onHoverState.IconRightImage = null;
            this.adara_btn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.adara_btn.OnIdleState.BorderRadius = 1;
            this.adara_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.adara_btn.OnIdleState.BorderThickness = 1;
            this.adara_btn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.adara_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.adara_btn.OnIdleState.IconLeftImage = null;
            this.adara_btn.OnIdleState.IconRightImage = null;
            this.adara_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.adara_btn.OnPressedState.BorderRadius = 1;
            this.adara_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.adara_btn.OnPressedState.BorderThickness = 1;
            this.adara_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.adara_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.adara_btn.OnPressedState.IconLeftImage = null;
            this.adara_btn.OnPressedState.IconRightImage = null;
            this.adara_btn.Size = new System.Drawing.Size(145, 27);
            this.adara_btn.TabIndex = 22;
            this.adara_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.adara_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.adara_btn.TextMarginLeft = 0;
            this.adara_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.adara_btn.UseDefaultRadiusAndThickness = true;
            this.adara_btn.Click += new System.EventHandler(this.adara_btn_Click);
            // 
            // tariharamabtn
            // 
            this.tariharamabtn.AllowAnimations = true;
            this.tariharamabtn.AllowMouseEffects = true;
            this.tariharamabtn.AllowToggling = false;
            this.tariharamabtn.AnimationSpeed = 200;
            this.tariharamabtn.AutoGenerateColors = false;
            this.tariharamabtn.AutoRoundBorders = false;
            this.tariharamabtn.AutoSizeLeftIcon = true;
            this.tariharamabtn.AutoSizeRightIcon = true;
            this.tariharamabtn.BackColor = System.Drawing.Color.Transparent;
            this.tariharamabtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.tariharamabtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tariharamabtn.BackgroundImage")));
            this.tariharamabtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tariharamabtn.ButtonText = "Tarih Aralığı Girerek Arama";
            this.tariharamabtn.ButtonTextMarginLeft = 0;
            this.tariharamabtn.ColorContrastOnClick = 45;
            this.tariharamabtn.ColorContrastOnHover = 45;
            this.tariharamabtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.tariharamabtn.CustomizableEdges = borderEdges5;
            this.tariharamabtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tariharamabtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tariharamabtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tariharamabtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tariharamabtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tariharamabtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.tariharamabtn.ForeColor = System.Drawing.Color.White;
            this.tariharamabtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tariharamabtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.tariharamabtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tariharamabtn.IconMarginLeft = 11;
            this.tariharamabtn.IconPadding = 10;
            this.tariharamabtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tariharamabtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.tariharamabtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tariharamabtn.IconSize = 25;
            this.tariharamabtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.tariharamabtn.IdleBorderRadius = 1;
            this.tariharamabtn.IdleBorderThickness = 1;
            this.tariharamabtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.tariharamabtn.IdleIconLeftImage = null;
            this.tariharamabtn.IdleIconRightImage = null;
            this.tariharamabtn.IndicateFocus = false;
            this.tariharamabtn.Location = new System.Drawing.Point(627, 49);
            this.tariharamabtn.Name = "tariharamabtn";
            this.tariharamabtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tariharamabtn.OnDisabledState.BorderRadius = 1;
            this.tariharamabtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tariharamabtn.OnDisabledState.BorderThickness = 1;
            this.tariharamabtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tariharamabtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tariharamabtn.OnDisabledState.IconLeftImage = null;
            this.tariharamabtn.OnDisabledState.IconRightImage = null;
            this.tariharamabtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tariharamabtn.onHoverState.BorderRadius = 1;
            this.tariharamabtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tariharamabtn.onHoverState.BorderThickness = 1;
            this.tariharamabtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tariharamabtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.tariharamabtn.onHoverState.IconLeftImage = null;
            this.tariharamabtn.onHoverState.IconRightImage = null;
            this.tariharamabtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.tariharamabtn.OnIdleState.BorderRadius = 1;
            this.tariharamabtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tariharamabtn.OnIdleState.BorderThickness = 1;
            this.tariharamabtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.tariharamabtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tariharamabtn.OnIdleState.IconLeftImage = null;
            this.tariharamabtn.OnIdleState.IconRightImage = null;
            this.tariharamabtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.tariharamabtn.OnPressedState.BorderRadius = 1;
            this.tariharamabtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tariharamabtn.OnPressedState.BorderThickness = 1;
            this.tariharamabtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.tariharamabtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.tariharamabtn.OnPressedState.IconLeftImage = null;
            this.tariharamabtn.OnPressedState.IconRightImage = null;
            this.tariharamabtn.Size = new System.Drawing.Size(145, 27);
            this.tariharamabtn.TabIndex = 23;
            this.tariharamabtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tariharamabtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tariharamabtn.TextMarginLeft = 0;
            this.tariharamabtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.tariharamabtn.UseDefaultRadiusAndThickness = true;
            this.tariharamabtn.Click += new System.EventHandler(this.tariharamabtn_Click);
            // 
            // cksbtn
            // 
            this.cksbtn.AllowAnimations = true;
            this.cksbtn.AllowMouseEffects = true;
            this.cksbtn.AllowToggling = false;
            this.cksbtn.AnimationSpeed = 200;
            this.cksbtn.AutoGenerateColors = false;
            this.cksbtn.AutoRoundBorders = false;
            this.cksbtn.AutoSizeLeftIcon = true;
            this.cksbtn.AutoSizeRightIcon = true;
            this.cksbtn.BackColor = System.Drawing.Color.Transparent;
            this.cksbtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.cksbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cksbtn.BackgroundImage")));
            this.cksbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.ButtonText = "X";
            this.cksbtn.ButtonTextMarginLeft = 0;
            this.cksbtn.ColorContrastOnClick = 45;
            this.cksbtn.ColorContrastOnHover = 45;
            this.cksbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.cksbtn.CustomizableEdges = borderEdges6;
            this.cksbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cksbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cksbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cksbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cksbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cksbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cksbtn.ForeColor = System.Drawing.Color.White;
            this.cksbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cksbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cksbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cksbtn.IconMarginLeft = 11;
            this.cksbtn.IconPadding = 10;
            this.cksbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cksbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cksbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cksbtn.IconSize = 25;
            this.cksbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.IdleBorderRadius = 15;
            this.cksbtn.IdleBorderThickness = 1;
            this.cksbtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.IdleIconLeftImage = null;
            this.cksbtn.IdleIconRightImage = null;
            this.cksbtn.IndicateFocus = false;
            this.cksbtn.Location = new System.Drawing.Point(771, 2);
            this.cksbtn.Name = "cksbtn";
            this.cksbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cksbtn.OnDisabledState.BorderRadius = 15;
            this.cksbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnDisabledState.BorderThickness = 1;
            this.cksbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cksbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cksbtn.OnDisabledState.IconLeftImage = null;
            this.cksbtn.OnDisabledState.IconRightImage = null;
            this.cksbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cksbtn.onHoverState.BorderRadius = 15;
            this.cksbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.onHoverState.BorderThickness = 1;
            this.cksbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cksbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.onHoverState.IconLeftImage = null;
            this.cksbtn.onHoverState.IconRightImage = null;
            this.cksbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.OnIdleState.BorderRadius = 15;
            this.cksbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnIdleState.BorderThickness = 1;
            this.cksbtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.OnIdleState.IconLeftImage = null;
            this.cksbtn.OnIdleState.IconRightImage = null;
            this.cksbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cksbtn.OnPressedState.BorderRadius = 15;
            this.cksbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnPressedState.BorderThickness = 1;
            this.cksbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cksbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.OnPressedState.IconLeftImage = null;
            this.cksbtn.OnPressedState.IconRightImage = null;
            this.cksbtn.Size = new System.Drawing.Size(26, 27);
            this.cksbtn.TabIndex = 25;
            this.cksbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cksbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cksbtn.TextMarginLeft = 0;
            this.cksbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cksbtn.UseDefaultRadiusAndThickness = true;
            this.cksbtn.Click += new System.EventHandler(this.cksbtn_Click);
            // 
            // backbtn
            // 
            this.backbtn.AllowAnimations = true;
            this.backbtn.AllowMouseEffects = true;
            this.backbtn.AllowToggling = false;
            this.backbtn.AnimationSpeed = 200;
            this.backbtn.AutoGenerateColors = false;
            this.backbtn.AutoRoundBorders = false;
            this.backbtn.AutoSizeLeftIcon = true;
            this.backbtn.AutoSizeRightIcon = true;
            this.backbtn.BackColor = System.Drawing.Color.Transparent;
            this.backbtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.backbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("backbtn.BackgroundImage")));
            this.backbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.ButtonText = "<-";
            this.backbtn.ButtonTextMarginLeft = 0;
            this.backbtn.ColorContrastOnClick = 45;
            this.backbtn.ColorContrastOnHover = 45;
            this.backbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.backbtn.CustomizableEdges = borderEdges7;
            this.backbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.backbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.backbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.backbtn.ForeColor = System.Drawing.Color.White;
            this.backbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.backbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.backbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.backbtn.IconMarginLeft = 11;
            this.backbtn.IconPadding = 10;
            this.backbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.backbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.backbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.backbtn.IconSize = 25;
            this.backbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.IdleBorderRadius = 15;
            this.backbtn.IdleBorderThickness = 1;
            this.backbtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.IdleIconLeftImage = null;
            this.backbtn.IdleIconRightImage = null;
            this.backbtn.IndicateFocus = false;
            this.backbtn.Location = new System.Drawing.Point(1, 2);
            this.backbtn.Name = "backbtn";
            this.backbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backbtn.OnDisabledState.BorderRadius = 15;
            this.backbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnDisabledState.BorderThickness = 1;
            this.backbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backbtn.OnDisabledState.IconLeftImage = null;
            this.backbtn.OnDisabledState.IconRightImage = null;
            this.backbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.backbtn.onHoverState.BorderRadius = 15;
            this.backbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.onHoverState.BorderThickness = 1;
            this.backbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.backbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.backbtn.onHoverState.IconLeftImage = null;
            this.backbtn.onHoverState.IconRightImage = null;
            this.backbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.OnIdleState.BorderRadius = 15;
            this.backbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnIdleState.BorderThickness = 1;
            this.backbtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.backbtn.OnIdleState.IconLeftImage = null;
            this.backbtn.OnIdleState.IconRightImage = null;
            this.backbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.backbtn.OnPressedState.BorderRadius = 15;
            this.backbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnPressedState.BorderThickness = 1;
            this.backbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.backbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.backbtn.OnPressedState.IconLeftImage = null;
            this.backbtn.OnPressedState.IconRightImage = null;
            this.backbtn.Size = new System.Drawing.Size(26, 27);
            this.backbtn.TabIndex = 24;
            this.backbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.backbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.backbtn.TextMarginLeft = 0;
            this.backbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.backbtn.UseDefaultRadiusAndThickness = true;
            this.backbtn.Click += new System.EventHandler(this.backbtn_Click);
            // 
            // AnaSayfa
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 500);
            this.Controls.Add(this.cksbtn);
            this.Controls.Add(this.backbtn);
            this.Controls.Add(this.tariharamabtn);
            this.Controls.Add(this.adara_btn);
            this.Controls.Add(this.prgrmbaz_btn);
            this.Controls.Add(this.gnbzli_btn);
            this.Controls.Add(this.usercontrl);
            this.Controls.Add(this.isrtbtn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "AnaSayfa";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AnaSayfa";
            this.Load += new System.EventHandler(this.AnaSayfa_Load);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel usercontrl;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton gnbzli_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton prgrmbaz_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton isrtbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton adara_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tariharamabtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cksbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton backbtn;
    }
}