namespace DouYonetim
{
    partial class YonetimPaneli
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(YonetimPaneli));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.cksbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.backbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.yizinekle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.gnclleakademisyen = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.akademisyensil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.akademisyenekle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.isrtbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.iizinekle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.usercontrl = new System.Windows.Forms.Panel();
            this.SuspendLayout();
            // 
            // cksbtn
            // 
            this.cksbtn.AllowAnimations = true;
            this.cksbtn.AllowMouseEffects = true;
            this.cksbtn.AllowToggling = false;
            this.cksbtn.AnimationSpeed = 200;
            this.cksbtn.AutoGenerateColors = false;
            this.cksbtn.AutoRoundBorders = false;
            this.cksbtn.AutoSizeLeftIcon = true;
            this.cksbtn.AutoSizeRightIcon = true;
            this.cksbtn.BackColor = System.Drawing.Color.Transparent;
            this.cksbtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.cksbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cksbtn.BackgroundImage")));
            this.cksbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.ButtonText = "X";
            this.cksbtn.ButtonTextMarginLeft = 0;
            this.cksbtn.ColorContrastOnClick = 45;
            this.cksbtn.ColorContrastOnHover = 45;
            this.cksbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.cksbtn.CustomizableEdges = borderEdges1;
            this.cksbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cksbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cksbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cksbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cksbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cksbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cksbtn.ForeColor = System.Drawing.Color.White;
            this.cksbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cksbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cksbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cksbtn.IconMarginLeft = 11;
            this.cksbtn.IconPadding = 10;
            this.cksbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cksbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cksbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cksbtn.IconSize = 25;
            this.cksbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.IdleBorderRadius = 15;
            this.cksbtn.IdleBorderThickness = 1;
            this.cksbtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.IdleIconLeftImage = null;
            this.cksbtn.IdleIconRightImage = null;
            this.cksbtn.IndicateFocus = false;
            this.cksbtn.Location = new System.Drawing.Point(771, 2);
            this.cksbtn.Name = "cksbtn";
            this.cksbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cksbtn.OnDisabledState.BorderRadius = 15;
            this.cksbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnDisabledState.BorderThickness = 1;
            this.cksbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cksbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cksbtn.OnDisabledState.IconLeftImage = null;
            this.cksbtn.OnDisabledState.IconRightImage = null;
            this.cksbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cksbtn.onHoverState.BorderRadius = 15;
            this.cksbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.onHoverState.BorderThickness = 1;
            this.cksbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cksbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.onHoverState.IconLeftImage = null;
            this.cksbtn.onHoverState.IconRightImage = null;
            this.cksbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.OnIdleState.BorderRadius = 15;
            this.cksbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnIdleState.BorderThickness = 1;
            this.cksbtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.cksbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.OnIdleState.IconLeftImage = null;
            this.cksbtn.OnIdleState.IconRightImage = null;
            this.cksbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cksbtn.OnPressedState.BorderRadius = 15;
            this.cksbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cksbtn.OnPressedState.BorderThickness = 1;
            this.cksbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cksbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.cksbtn.OnPressedState.IconLeftImage = null;
            this.cksbtn.OnPressedState.IconRightImage = null;
            this.cksbtn.Size = new System.Drawing.Size(26, 27);
            this.cksbtn.TabIndex = 18;
            this.cksbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cksbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cksbtn.TextMarginLeft = 0;
            this.cksbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cksbtn.UseDefaultRadiusAndThickness = true;
            this.cksbtn.Click += new System.EventHandler(this.cksbtn_Click);
            // 
            // backbtn
            // 
            this.backbtn.AllowAnimations = true;
            this.backbtn.AllowMouseEffects = true;
            this.backbtn.AllowToggling = false;
            this.backbtn.AnimationSpeed = 200;
            this.backbtn.AutoGenerateColors = false;
            this.backbtn.AutoRoundBorders = false;
            this.backbtn.AutoSizeLeftIcon = true;
            this.backbtn.AutoSizeRightIcon = true;
            this.backbtn.BackColor = System.Drawing.Color.Transparent;
            this.backbtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.backbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("backbtn.BackgroundImage")));
            this.backbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.ButtonText = "<-";
            this.backbtn.ButtonTextMarginLeft = 0;
            this.backbtn.ColorContrastOnClick = 45;
            this.backbtn.ColorContrastOnHover = 45;
            this.backbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.backbtn.CustomizableEdges = borderEdges2;
            this.backbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.backbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.backbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.backbtn.ForeColor = System.Drawing.Color.White;
            this.backbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.backbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.backbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.backbtn.IconMarginLeft = 11;
            this.backbtn.IconPadding = 10;
            this.backbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.backbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.backbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.backbtn.IconSize = 25;
            this.backbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.IdleBorderRadius = 15;
            this.backbtn.IdleBorderThickness = 1;
            this.backbtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.IdleIconLeftImage = null;
            this.backbtn.IdleIconRightImage = null;
            this.backbtn.IndicateFocus = false;
            this.backbtn.Location = new System.Drawing.Point(1, 2);
            this.backbtn.Name = "backbtn";
            this.backbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backbtn.OnDisabledState.BorderRadius = 15;
            this.backbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnDisabledState.BorderThickness = 1;
            this.backbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backbtn.OnDisabledState.IconLeftImage = null;
            this.backbtn.OnDisabledState.IconRightImage = null;
            this.backbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.backbtn.onHoverState.BorderRadius = 15;
            this.backbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.onHoverState.BorderThickness = 1;
            this.backbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.backbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.backbtn.onHoverState.IconLeftImage = null;
            this.backbtn.onHoverState.IconRightImage = null;
            this.backbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.OnIdleState.BorderRadius = 15;
            this.backbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnIdleState.BorderThickness = 1;
            this.backbtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.backbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.backbtn.OnIdleState.IconLeftImage = null;
            this.backbtn.OnIdleState.IconRightImage = null;
            this.backbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.backbtn.OnPressedState.BorderRadius = 15;
            this.backbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backbtn.OnPressedState.BorderThickness = 1;
            this.backbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.backbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.backbtn.OnPressedState.IconLeftImage = null;
            this.backbtn.OnPressedState.IconRightImage = null;
            this.backbtn.Size = new System.Drawing.Size(26, 27);
            this.backbtn.TabIndex = 17;
            this.backbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.backbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.backbtn.TextMarginLeft = 0;
            this.backbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.backbtn.UseDefaultRadiusAndThickness = true;
            this.backbtn.Click += new System.EventHandler(this.backbtn_Click);
            // 
            // yizinekle
            // 
            this.yizinekle.AllowAnimations = true;
            this.yizinekle.AllowMouseEffects = true;
            this.yizinekle.AllowToggling = false;
            this.yizinekle.AnimationSpeed = 200;
            this.yizinekle.AutoGenerateColors = false;
            this.yizinekle.AutoRoundBorders = false;
            this.yizinekle.AutoSizeLeftIcon = true;
            this.yizinekle.AutoSizeRightIcon = true;
            this.yizinekle.BackColor = System.Drawing.Color.Transparent;
            this.yizinekle.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.yizinekle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yizinekle.BackgroundImage")));
            this.yizinekle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.yizinekle.ButtonText = "Yıllık İzin Ekle";
            this.yizinekle.ButtonTextMarginLeft = 0;
            this.yizinekle.ColorContrastOnClick = 45;
            this.yizinekle.ColorContrastOnHover = 45;
            this.yizinekle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.yizinekle.CustomizableEdges = borderEdges3;
            this.yizinekle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.yizinekle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.yizinekle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yizinekle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.yizinekle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.yizinekle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.yizinekle.ForeColor = System.Drawing.Color.White;
            this.yizinekle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.yizinekle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.yizinekle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.yizinekle.IconMarginLeft = 11;
            this.yizinekle.IconPadding = 10;
            this.yizinekle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.yizinekle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.yizinekle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.yizinekle.IconSize = 25;
            this.yizinekle.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.yizinekle.IdleBorderRadius = 1;
            this.yizinekle.IdleBorderThickness = 1;
            this.yizinekle.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.yizinekle.IdleIconLeftImage = null;
            this.yizinekle.IdleIconRightImage = null;
            this.yizinekle.IndicateFocus = false;
            this.yizinekle.Location = new System.Drawing.Point(477, 49);
            this.yizinekle.Name = "yizinekle";
            this.yizinekle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.yizinekle.OnDisabledState.BorderRadius = 1;
            this.yizinekle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.yizinekle.OnDisabledState.BorderThickness = 1;
            this.yizinekle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yizinekle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.yizinekle.OnDisabledState.IconLeftImage = null;
            this.yizinekle.OnDisabledState.IconRightImage = null;
            this.yizinekle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yizinekle.onHoverState.BorderRadius = 1;
            this.yizinekle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.yizinekle.onHoverState.BorderThickness = 1;
            this.yizinekle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yizinekle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.yizinekle.onHoverState.IconLeftImage = null;
            this.yizinekle.onHoverState.IconRightImage = null;
            this.yizinekle.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.yizinekle.OnIdleState.BorderRadius = 1;
            this.yizinekle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.yizinekle.OnIdleState.BorderThickness = 1;
            this.yizinekle.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.yizinekle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.yizinekle.OnIdleState.IconLeftImage = null;
            this.yizinekle.OnIdleState.IconRightImage = null;
            this.yizinekle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.yizinekle.OnPressedState.BorderRadius = 1;
            this.yizinekle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.yizinekle.OnPressedState.BorderThickness = 1;
            this.yizinekle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.yizinekle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.yizinekle.OnPressedState.IconLeftImage = null;
            this.yizinekle.OnPressedState.IconRightImage = null;
            this.yizinekle.Size = new System.Drawing.Size(145, 27);
            this.yizinekle.TabIndex = 27;
            this.yizinekle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.yizinekle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.yizinekle.TextMarginLeft = 0;
            this.yizinekle.TextPadding = new System.Windows.Forms.Padding(0);
            this.yizinekle.UseDefaultRadiusAndThickness = true;
            this.yizinekle.Click += new System.EventHandler(this.yizinekle_Click);
            // 
            // gnclleakademisyen
            // 
            this.gnclleakademisyen.AllowAnimations = true;
            this.gnclleakademisyen.AllowMouseEffects = true;
            this.gnclleakademisyen.AllowToggling = false;
            this.gnclleakademisyen.AnimationSpeed = 200;
            this.gnclleakademisyen.AutoGenerateColors = false;
            this.gnclleakademisyen.AutoRoundBorders = false;
            this.gnclleakademisyen.AutoSizeLeftIcon = true;
            this.gnclleakademisyen.AutoSizeRightIcon = true;
            this.gnclleakademisyen.BackColor = System.Drawing.Color.Transparent;
            this.gnclleakademisyen.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.gnclleakademisyen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gnclleakademisyen.BackgroundImage")));
            this.gnclleakademisyen.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnclleakademisyen.ButtonText = "Akademisyen Güncelle";
            this.gnclleakademisyen.ButtonTextMarginLeft = 0;
            this.gnclleakademisyen.ColorContrastOnClick = 45;
            this.gnclleakademisyen.ColorContrastOnHover = 45;
            this.gnclleakademisyen.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.gnclleakademisyen.CustomizableEdges = borderEdges4;
            this.gnclleakademisyen.DialogResult = System.Windows.Forms.DialogResult.None;
            this.gnclleakademisyen.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gnclleakademisyen.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gnclleakademisyen.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gnclleakademisyen.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.gnclleakademisyen.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gnclleakademisyen.ForeColor = System.Drawing.Color.White;
            this.gnclleakademisyen.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.gnclleakademisyen.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.gnclleakademisyen.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.gnclleakademisyen.IconMarginLeft = 11;
            this.gnclleakademisyen.IconPadding = 10;
            this.gnclleakademisyen.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.gnclleakademisyen.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.gnclleakademisyen.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.gnclleakademisyen.IconSize = 25;
            this.gnclleakademisyen.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.gnclleakademisyen.IdleBorderRadius = 1;
            this.gnclleakademisyen.IdleBorderThickness = 1;
            this.gnclleakademisyen.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.gnclleakademisyen.IdleIconLeftImage = null;
            this.gnclleakademisyen.IdleIconRightImage = null;
            this.gnclleakademisyen.IndicateFocus = false;
            this.gnclleakademisyen.Location = new System.Drawing.Point(326, 49);
            this.gnclleakademisyen.Name = "gnclleakademisyen";
            this.gnclleakademisyen.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gnclleakademisyen.OnDisabledState.BorderRadius = 1;
            this.gnclleakademisyen.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnclleakademisyen.OnDisabledState.BorderThickness = 1;
            this.gnclleakademisyen.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gnclleakademisyen.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gnclleakademisyen.OnDisabledState.IconLeftImage = null;
            this.gnclleakademisyen.OnDisabledState.IconRightImage = null;
            this.gnclleakademisyen.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gnclleakademisyen.onHoverState.BorderRadius = 1;
            this.gnclleakademisyen.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnclleakademisyen.onHoverState.BorderThickness = 1;
            this.gnclleakademisyen.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gnclleakademisyen.onHoverState.ForeColor = System.Drawing.Color.White;
            this.gnclleakademisyen.onHoverState.IconLeftImage = null;
            this.gnclleakademisyen.onHoverState.IconRightImage = null;
            this.gnclleakademisyen.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.gnclleakademisyen.OnIdleState.BorderRadius = 1;
            this.gnclleakademisyen.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnclleakademisyen.OnIdleState.BorderThickness = 1;
            this.gnclleakademisyen.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.gnclleakademisyen.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.gnclleakademisyen.OnIdleState.IconLeftImage = null;
            this.gnclleakademisyen.OnIdleState.IconRightImage = null;
            this.gnclleakademisyen.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gnclleakademisyen.OnPressedState.BorderRadius = 1;
            this.gnclleakademisyen.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.gnclleakademisyen.OnPressedState.BorderThickness = 1;
            this.gnclleakademisyen.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gnclleakademisyen.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.gnclleakademisyen.OnPressedState.IconLeftImage = null;
            this.gnclleakademisyen.OnPressedState.IconRightImage = null;
            this.gnclleakademisyen.Size = new System.Drawing.Size(145, 27);
            this.gnclleakademisyen.TabIndex = 25;
            this.gnclleakademisyen.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gnclleakademisyen.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.gnclleakademisyen.TextMarginLeft = 0;
            this.gnclleakademisyen.TextPadding = new System.Windows.Forms.Padding(0);
            this.gnclleakademisyen.UseDefaultRadiusAndThickness = true;
            this.gnclleakademisyen.Click += new System.EventHandler(this.gnclleakademisyen_Click);
            // 
            // akademisyensil
            // 
            this.akademisyensil.AllowAnimations = true;
            this.akademisyensil.AllowMouseEffects = true;
            this.akademisyensil.AllowToggling = false;
            this.akademisyensil.AnimationSpeed = 200;
            this.akademisyensil.AutoGenerateColors = false;
            this.akademisyensil.AutoRoundBorders = false;
            this.akademisyensil.AutoSizeLeftIcon = true;
            this.akademisyensil.AutoSizeRightIcon = true;
            this.akademisyensil.BackColor = System.Drawing.Color.Transparent;
            this.akademisyensil.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.akademisyensil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("akademisyensil.BackgroundImage")));
            this.akademisyensil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyensil.ButtonText = "Akademisyen Sil";
            this.akademisyensil.ButtonTextMarginLeft = 0;
            this.akademisyensil.ColorContrastOnClick = 45;
            this.akademisyensil.ColorContrastOnHover = 45;
            this.akademisyensil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.akademisyensil.CustomizableEdges = borderEdges5;
            this.akademisyensil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.akademisyensil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.akademisyensil.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.akademisyensil.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.akademisyensil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.akademisyensil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.akademisyensil.ForeColor = System.Drawing.Color.White;
            this.akademisyensil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.akademisyensil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.akademisyensil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.akademisyensil.IconMarginLeft = 11;
            this.akademisyensil.IconPadding = 10;
            this.akademisyensil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.akademisyensil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.akademisyensil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.akademisyensil.IconSize = 25;
            this.akademisyensil.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.akademisyensil.IdleBorderRadius = 1;
            this.akademisyensil.IdleBorderThickness = 1;
            this.akademisyensil.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.akademisyensil.IdleIconLeftImage = null;
            this.akademisyensil.IdleIconRightImage = null;
            this.akademisyensil.IndicateFocus = false;
            this.akademisyensil.Location = new System.Drawing.Point(175, 49);
            this.akademisyensil.Name = "akademisyensil";
            this.akademisyensil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.akademisyensil.OnDisabledState.BorderRadius = 1;
            this.akademisyensil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyensil.OnDisabledState.BorderThickness = 1;
            this.akademisyensil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.akademisyensil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.akademisyensil.OnDisabledState.IconLeftImage = null;
            this.akademisyensil.OnDisabledState.IconRightImage = null;
            this.akademisyensil.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.akademisyensil.onHoverState.BorderRadius = 1;
            this.akademisyensil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyensil.onHoverState.BorderThickness = 1;
            this.akademisyensil.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.akademisyensil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.akademisyensil.onHoverState.IconLeftImage = null;
            this.akademisyensil.onHoverState.IconRightImage = null;
            this.akademisyensil.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.akademisyensil.OnIdleState.BorderRadius = 1;
            this.akademisyensil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyensil.OnIdleState.BorderThickness = 1;
            this.akademisyensil.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.akademisyensil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.akademisyensil.OnIdleState.IconLeftImage = null;
            this.akademisyensil.OnIdleState.IconRightImage = null;
            this.akademisyensil.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.akademisyensil.OnPressedState.BorderRadius = 1;
            this.akademisyensil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyensil.OnPressedState.BorderThickness = 1;
            this.akademisyensil.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.akademisyensil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.akademisyensil.OnPressedState.IconLeftImage = null;
            this.akademisyensil.OnPressedState.IconRightImage = null;
            this.akademisyensil.Size = new System.Drawing.Size(145, 27);
            this.akademisyensil.TabIndex = 24;
            this.akademisyensil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.akademisyensil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.akademisyensil.TextMarginLeft = 0;
            this.akademisyensil.TextPadding = new System.Windows.Forms.Padding(0);
            this.akademisyensil.UseDefaultRadiusAndThickness = true;
            this.akademisyensil.Click += new System.EventHandler(this.akademisyensil_Click);
            // 
            // akademisyenekle
            // 
            this.akademisyenekle.AllowAnimations = true;
            this.akademisyenekle.AllowMouseEffects = true;
            this.akademisyenekle.AllowToggling = false;
            this.akademisyenekle.AnimationSpeed = 200;
            this.akademisyenekle.AutoGenerateColors = false;
            this.akademisyenekle.AutoRoundBorders = false;
            this.akademisyenekle.AutoSizeLeftIcon = true;
            this.akademisyenekle.AutoSizeRightIcon = true;
            this.akademisyenekle.BackColor = System.Drawing.Color.Transparent;
            this.akademisyenekle.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.akademisyenekle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("akademisyenekle.BackgroundImage")));
            this.akademisyenekle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyenekle.ButtonText = "Akademisyen Ekle";
            this.akademisyenekle.ButtonTextMarginLeft = 0;
            this.akademisyenekle.ColorContrastOnClick = 45;
            this.akademisyenekle.ColorContrastOnHover = 45;
            this.akademisyenekle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.akademisyenekle.CustomizableEdges = borderEdges6;
            this.akademisyenekle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.akademisyenekle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.akademisyenekle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.akademisyenekle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.akademisyenekle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.akademisyenekle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.akademisyenekle.ForeColor = System.Drawing.Color.White;
            this.akademisyenekle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.akademisyenekle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.akademisyenekle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.akademisyenekle.IconMarginLeft = 11;
            this.akademisyenekle.IconPadding = 10;
            this.akademisyenekle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.akademisyenekle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.akademisyenekle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.akademisyenekle.IconSize = 25;
            this.akademisyenekle.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.akademisyenekle.IdleBorderRadius = 1;
            this.akademisyenekle.IdleBorderThickness = 1;
            this.akademisyenekle.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.akademisyenekle.IdleIconLeftImage = null;
            this.akademisyenekle.IdleIconRightImage = null;
            this.akademisyenekle.IndicateFocus = false;
            this.akademisyenekle.Location = new System.Drawing.Point(24, 49);
            this.akademisyenekle.Name = "akademisyenekle";
            this.akademisyenekle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.akademisyenekle.OnDisabledState.BorderRadius = 1;
            this.akademisyenekle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyenekle.OnDisabledState.BorderThickness = 1;
            this.akademisyenekle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.akademisyenekle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.akademisyenekle.OnDisabledState.IconLeftImage = null;
            this.akademisyenekle.OnDisabledState.IconRightImage = null;
            this.akademisyenekle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.akademisyenekle.onHoverState.BorderRadius = 1;
            this.akademisyenekle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyenekle.onHoverState.BorderThickness = 1;
            this.akademisyenekle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.akademisyenekle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.akademisyenekle.onHoverState.IconLeftImage = null;
            this.akademisyenekle.onHoverState.IconRightImage = null;
            this.akademisyenekle.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.akademisyenekle.OnIdleState.BorderRadius = 1;
            this.akademisyenekle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyenekle.OnIdleState.BorderThickness = 1;
            this.akademisyenekle.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.akademisyenekle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.akademisyenekle.OnIdleState.IconLeftImage = null;
            this.akademisyenekle.OnIdleState.IconRightImage = null;
            this.akademisyenekle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.akademisyenekle.OnPressedState.BorderRadius = 1;
            this.akademisyenekle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.akademisyenekle.OnPressedState.BorderThickness = 1;
            this.akademisyenekle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.akademisyenekle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.akademisyenekle.OnPressedState.IconLeftImage = null;
            this.akademisyenekle.OnPressedState.IconRightImage = null;
            this.akademisyenekle.Size = new System.Drawing.Size(145, 27);
            this.akademisyenekle.TabIndex = 23;
            this.akademisyenekle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.akademisyenekle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.akademisyenekle.TextMarginLeft = 0;
            this.akademisyenekle.TextPadding = new System.Windows.Forms.Padding(0);
            this.akademisyenekle.UseDefaultRadiusAndThickness = true;
            this.akademisyenekle.Click += new System.EventHandler(this.akademisyenekle_Click);
            // 
            // isrtbtn
            // 
            this.isrtbtn.AllowAnimations = true;
            this.isrtbtn.AllowMouseEffects = true;
            this.isrtbtn.AllowToggling = false;
            this.isrtbtn.AnimationSpeed = 200;
            this.isrtbtn.AutoGenerateColors = false;
            this.isrtbtn.AutoRoundBorders = false;
            this.isrtbtn.AutoSizeLeftIcon = true;
            this.isrtbtn.AutoSizeRightIcon = true;
            this.isrtbtn.BackColor = System.Drawing.Color.Transparent;
            this.isrtbtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("isrtbtn.BackgroundImage")));
            this.isrtbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.ButtonText = "";
            this.isrtbtn.ButtonTextMarginLeft = 0;
            this.isrtbtn.ColorContrastOnClick = 45;
            this.isrtbtn.ColorContrastOnHover = 45;
            this.isrtbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.isrtbtn.CustomizableEdges = borderEdges7;
            this.isrtbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.isrtbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.isrtbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isrtbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.isrtbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.isrtbtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.isrtbtn.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.isrtbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.isrtbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.isrtbtn.IconMarginLeft = 11;
            this.isrtbtn.IconPadding = 10;
            this.isrtbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.isrtbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.isrtbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.isrtbtn.IconSize = 25;
            this.isrtbtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.isrtbtn.IdleBorderRadius = 1;
            this.isrtbtn.IdleBorderThickness = 1;
            this.isrtbtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.IdleIconLeftImage = null;
            this.isrtbtn.IdleIconRightImage = null;
            this.isrtbtn.IndicateFocus = false;
            this.isrtbtn.Location = new System.Drawing.Point(171, 45);
            this.isrtbtn.Name = "isrtbtn";
            this.isrtbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.isrtbtn.OnDisabledState.BorderRadius = 1;
            this.isrtbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnDisabledState.BorderThickness = 1;
            this.isrtbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isrtbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.isrtbtn.OnDisabledState.IconLeftImage = null;
            this.isrtbtn.OnDisabledState.IconRightImage = null;
            this.isrtbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isrtbtn.onHoverState.BorderRadius = 1;
            this.isrtbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.onHoverState.BorderThickness = 1;
            this.isrtbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isrtbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.onHoverState.IconLeftImage = null;
            this.isrtbtn.onHoverState.IconRightImage = null;
            this.isrtbtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.isrtbtn.OnIdleState.BorderRadius = 1;
            this.isrtbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnIdleState.BorderThickness = 1;
            this.isrtbtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.isrtbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.OnIdleState.IconLeftImage = null;
            this.isrtbtn.OnIdleState.IconRightImage = null;
            this.isrtbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.isrtbtn.OnPressedState.BorderRadius = 1;
            this.isrtbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.isrtbtn.OnPressedState.BorderThickness = 1;
            this.isrtbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.isrtbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.isrtbtn.OnPressedState.IconLeftImage = null;
            this.isrtbtn.OnPressedState.IconRightImage = null;
            this.isrtbtn.Size = new System.Drawing.Size(153, 36);
            this.isrtbtn.TabIndex = 26;
            this.isrtbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.isrtbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.isrtbtn.TextMarginLeft = 0;
            this.isrtbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.isrtbtn.UseDefaultRadiusAndThickness = true;
            // 
            // iizinekle
            // 
            this.iizinekle.AllowAnimations = true;
            this.iizinekle.AllowMouseEffects = true;
            this.iizinekle.AllowToggling = false;
            this.iizinekle.AnimationSpeed = 200;
            this.iizinekle.AutoGenerateColors = false;
            this.iizinekle.AutoRoundBorders = false;
            this.iizinekle.AutoSizeLeftIcon = true;
            this.iizinekle.AutoSizeRightIcon = true;
            this.iizinekle.BackColor = System.Drawing.Color.Transparent;
            this.iizinekle.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.iizinekle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("iizinekle.BackgroundImage")));
            this.iizinekle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.iizinekle.ButtonText = "İdari İzin Ekle";
            this.iizinekle.ButtonTextMarginLeft = 0;
            this.iizinekle.ColorContrastOnClick = 45;
            this.iizinekle.ColorContrastOnHover = 45;
            this.iizinekle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.iizinekle.CustomizableEdges = borderEdges8;
            this.iizinekle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.iizinekle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.iizinekle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.iizinekle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.iizinekle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.iizinekle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.iizinekle.ForeColor = System.Drawing.Color.White;
            this.iizinekle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.iizinekle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.iizinekle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.iizinekle.IconMarginLeft = 11;
            this.iizinekle.IconPadding = 10;
            this.iizinekle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.iizinekle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.iizinekle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.iizinekle.IconSize = 25;
            this.iizinekle.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.iizinekle.IdleBorderRadius = 1;
            this.iizinekle.IdleBorderThickness = 1;
            this.iizinekle.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.iizinekle.IdleIconLeftImage = null;
            this.iizinekle.IdleIconRightImage = null;
            this.iizinekle.IndicateFocus = false;
            this.iizinekle.Location = new System.Drawing.Point(628, 49);
            this.iizinekle.Name = "iizinekle";
            this.iizinekle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.iizinekle.OnDisabledState.BorderRadius = 1;
            this.iizinekle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.iizinekle.OnDisabledState.BorderThickness = 1;
            this.iizinekle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.iizinekle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.iizinekle.OnDisabledState.IconLeftImage = null;
            this.iizinekle.OnDisabledState.IconRightImage = null;
            this.iizinekle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.iizinekle.onHoverState.BorderRadius = 1;
            this.iizinekle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.iizinekle.onHoverState.BorderThickness = 1;
            this.iizinekle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.iizinekle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.iizinekle.onHoverState.IconLeftImage = null;
            this.iizinekle.onHoverState.IconRightImage = null;
            this.iizinekle.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.iizinekle.OnIdleState.BorderRadius = 1;
            this.iizinekle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.iizinekle.OnIdleState.BorderThickness = 1;
            this.iizinekle.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.iizinekle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.iizinekle.OnIdleState.IconLeftImage = null;
            this.iizinekle.OnIdleState.IconRightImage = null;
            this.iizinekle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.iizinekle.OnPressedState.BorderRadius = 1;
            this.iizinekle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.iizinekle.OnPressedState.BorderThickness = 1;
            this.iizinekle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.iizinekle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.iizinekle.OnPressedState.IconLeftImage = null;
            this.iizinekle.OnPressedState.IconRightImage = null;
            this.iizinekle.Size = new System.Drawing.Size(145, 27);
            this.iizinekle.TabIndex = 28;
            this.iizinekle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.iizinekle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.iizinekle.TextMarginLeft = 0;
            this.iizinekle.TextPadding = new System.Windows.Forms.Padding(0);
            this.iizinekle.UseDefaultRadiusAndThickness = true;
            this.iizinekle.Click += new System.EventHandler(this.iizinekle_Click);
            // 
            // usercontrl
            // 
            this.usercontrl.Location = new System.Drawing.Point(130, 87);
            this.usercontrl.Name = "usercontrl";
            this.usercontrl.Size = new System.Drawing.Size(539, 351);
            this.usercontrl.TabIndex = 29;
            // 
            // YonetimPaneli
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.usercontrl);
            this.Controls.Add(this.iizinekle);
            this.Controls.Add(this.yizinekle);
            this.Controls.Add(this.gnclleakademisyen);
            this.Controls.Add(this.akademisyensil);
            this.Controls.Add(this.akademisyenekle);
            this.Controls.Add(this.isrtbtn);
            this.Controls.Add(this.cksbtn);
            this.Controls.Add(this.backbtn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "YonetimPaneli";
            this.Text = "YonetimPaneli";
            this.Load += new System.EventHandler(this.YonetimPaneli_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cksbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton backbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton yizinekle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton gnclleakademisyen;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton akademisyensil;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton akademisyenekle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton isrtbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton iizinekle;
        private System.Windows.Forms.Panel usercontrl;
    }
}